name: Renovate

on:
  pull_request:

jobs:
  generate-changeset:
    runs-on: ubuntu-latest
    if: github.actor == 'renovate[bot]' && github.repository == 'mkizka/eslint-config'
    permissions:
      contents: write
    steps:
      # Changeset追加時にunit-testなどをトリガーするためにトークンを取得する
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}
      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          # この指定がないとブランチ名が`pull/XXX/merge`になってしまう
          ref: ${{ github.head_ref }}
          # changeset-renovateがHEAD~1を取得するために必要
          fetch-depth: 2
      - name: Run @scaleway/changesets-renovate
        run: |
          git config --global user.name github-actions[bot]
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
          npx @scaleway/changesets-renovate
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'renovate[bot]' && github.repository == 'mkizka/eslint-config'
    needs: generate-changeset
    permissions:
      contents: write
      pull-requests: write
    steps:
      - run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
